project := achilles
#CPPFLAGS += -g -D_DEBUG 
CPPFLAGS += -g -D_DEBUG 
CXXFLAGS += -Wfatal-errors
#LINKFLAGS := --static -lzmq -lboost_regex -lboost_thread -lboost_program_options -lboost_chrono -lboost_system -lpthread
LINKFLAGS := --static -lzmq -lboost_thread -lboost_program_options -lboost_chrono -lpthread

.PHONY:

all: $(project)

include ../common.mk
